name: Test package

on:
  push:
    # The CI is executed on every push on to main
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
  
jobs:

  test-code:
    # This code depends on the result of check-code
    runs-on: macos-12
    container:
      image: julia:latest

      - uses: actions/checkout@v3
      
      - name: Run script
        run: julia helloworld.jl

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
        name: Figures
          path: plots
          retention-days: 90
          if-no-files-found: error
